### ISSUE TITLE
Add Hungarian to suported Langs

### ISSUE THREAD

**Issue by ganz79** [openedx/openedx-i18n#13]
Dear Team,

Could you please add Hungarian (hu) language to openedx-i18n project?

Many thanks,
Mihaly

**Comment by ganz79** [comment]
Hi, 
It worked with Lilac but the latest Tutor/Maple version not.
Many thanks,
Mihaly

**Comment by ganz79** [comment]
Hi, After I deleted the cookies now it works in Hungarian language. Many thanks, Mihaly

**Comment by ganz79** [comment]
Sorry, this is still an issue. When I login to LMS front end I couldn't choose "hu" language and openedx-language-preference cookie is showing "en" instead of "hu". tutor-MFE also in English language.

Is this issue because of the translation status under 50% on Transifex?

**Comment by regisb** [comment]
> Is this issue because of the translation status under 50% on Transifex?

Yes, this is correct. Translations are pulled only for languages that include >50% of _verified_ translations. To increase that number for the Hungarian language, you should get in touch with the Transifex working group: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3157524644/Transifex+Working+Group

I'll close this now. Please get in touch again via the [Tutor forum](https://discuss.overhang.io/) when the rate of verified translations has increased.
