### ISSUE TITLE
Persian Language Support 

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/openedx-i18n#17]
Hi everyone
our translation team at edSpirit did one hell of a job and translated the entire Persian Language (fa_IR). the language state is 100% translated and reviewed.
I've added `fa_IR` code to the locales list in the `config-extra.yaml` and `django.po`, `django.mo`, `djangojs.po`, and `djangojs.mo` files in the ` edx-platform/locale/fa_IR/LC_MESSAGES/` directory.
you can find it here, in this [PR](https://github.com/openedx/openedx-i18n/pull/16).

**Comment by CodeWithEmad** [comment]
@regisb  you can also close https://github.com/openedx/openedx-i18n/issues/11 (old issue from 2020) if this was merged.

**Comment by regisb** [comment]
Closed by #16
