### ISSUE TITLE
Could you please add zh_CN # Chinese (China)?

### ISSUE THREAD

**Issue by kikoShen** [openedx/openedx-i18n#3]
I just find  zh_TW,  I'm really appreciate your adding it!

**Comment by regisb** [comment]
Hi @kikoShen! The zh_CN locale is already included in edx-platform, so I don't really see the use of adding it here. This repo only includes extra locales that are not included by default in edx-platform. Did you have issues localizing edx-platform in Chinese?

**Comment by kikoShen** [comment]
I'm so so sorry! i find it!

**Comment by regisb** [comment]
:+1:
