### ISSUE TITLE
Can we archive this repo in favor of openedx-translations?

### ISSUE THREAD

**Issue by kdmccormick** [openedx/openedx-i18n#31]
As I understand it, this repos was fulfulling a need that is now served by https://github.com/openedx/openedx-translations.

@regisb , can you confirm that? If so, shall I just archive this, or would you like it to go through the DEPR process?

**Comment by regisb** [comment]
Yes, I confirm that. We should just make sure that this repo is still available for older releases. Thus, archiving should work -- we should simply be careful not to delete it.

**Comment by kdmccormick** [comment]
got it 👍🏻
