### ISSUE TITLE
How to modify Django.po

### ISSUE THREAD

**Issue by arsenal0927** [openedx/openedx-i18n#7]
hello regisb!
Sometimes, I need to modify the contents of a file, such as djang.po, but i didn't find the way.
Can you give some advice to solve this problem?
thank you!
And sorry for my terrible English.

**Comment by regisb** [comment]
Hi @ArsenalLevel3! Sorry for the delay on answering your question. Are you trying to modify the files in [edx-platform](https://github.com/edx/edx-platform/)? If yes, you should simply modify the files and then re-compile the translations. To do so, I believe you should simply run something like [`./manage.py lms compilemessages`](https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#compiling-message-files). (I'm not too sure about that last command)

You would probably get a better answer by asking on the [official Open edX discussion forums](https://discuss.openedx.org).
