### ISSUE TITLE
Add Portuguese Brazilian to suported Langs

### ISSUE THREAD

**Issue by ejklock** [openedx/openedx-i18n#9]
Hello!
Could you add support for Portuguese language Brazil (pt-br) to get latest strings from transifex?

These can include .js files translation too?

thanks in advance

**Comment by regisb** [comment]
Sorry for my lack of reply... (3 years! How time flies :sweat_smile:)

The pt-br locale already ships with edx-platform, so there is no need to bundle the translation strings here in this project.
